### ISSUE TITLE
feat: healthcheck endpoint for the exporter

### ISSUE THREAD

**Issue by 42Atomys** [d1ceward/shellyplug-exporter#4]
**Is your feature request related to a problem? Please describe.**
When a plug or the exporter fall down into the deep of the world, and no data is exporter anymore, we needs to restart it manually.

**Describe the solution you'd like**
Add a healthcheck `/healthz` to validate the state of the exporter and state of plugs. 

**Additional context**

- When a plugs is unreachable : exporter is unhealthy due this connection issue 
- When the exporter is unreachable : exporter is unhealthy (of course)

**Comment by d1ceward** [comment]
Good addition, I will look at it when I have some free time, I think it can be done quickly

**Comment by d1ceward** [comment]
Released in [v1.4.0](https://github.com/d1ceward/shellyplug-exporter/releases/tag/v1.4.0)
